### PR TITLE
fix(apidoc): repair generated links

### LINKED ISSUE #513: Repair links in doc comments
The generated API documentation contains links that are not rendered properly, they should be switched to
https://api-extractor.com/pages/tsdoc/tag_link/ .

For example, https://influxdata.github.io/influxdb-client-js/influxdb-client.queryapi.querylines.html now shows:

Executes the query and receives result lines (including empty and
annotation lines) through the supplied consumer. See \[annotated-csv\]
(https://docs.influxdata.com/influxdb/v2.1/reference/syntax/annotated-csv/).

It must be repaired to show this:

Executes the query and receives result lines (including empty and
annotation lines) through the supplied consumer. See [annotated-csv](https://docs.influxdata.com/influxdb/v2.1/reference/syntax/annotated-csv/).

### PR DESCRIPTION
**Pull request by sranka**
Fixes #513

## Proposed Changes
- doc reviewed and improved
- change generated API links to point to InfluxDB v2.3
- change unsupported markdown links to TSdoc links before generation of API docs

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] `yarn test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

File: packages/core/src/QueryApi.ts [hunk 1]
```diff
@@ -73,7 +73,7 @@ export default interface QueryApi {
 
   /**
    * Executes the query and receives result lines (including empty and annotation lines)
-   * through the supplied consumer. See [annotated-csv](https://docs.influxdata.com/influxdb/v2.1/reference/syntax/annotated-csv/).
+   * through the supplied consumer. See [annotated-csv](https://docs.influxdata.com/influxdb/v2.3/reference/syntax/annotated-csv/).
```
Comment (bednar) [inline packages/core/src/QueryApi.ts:76]: Maybe the `latest` will be better:

```suggestion
   * through the supplied consumer. See [annotated-csv](https://docs.influxdata.com/influxdb/latest/reference/syntax/annotated-csv/).
```

File: packages/core/src/query/flux.ts [hunk 2]
```diff
@@ -39,7 +39,7 @@ function isFluxParameterLike(value: any): boolean {
 
 /**
  * Escapes content of the supplied string so it can be wrapped into double qoutes
- * to become a [flux string literal](https://docs.influxdata.com/flux/v0.65/language/lexical-elements/#string-literals).
+ * to become a [flux string literal](https://docs.influxdata.com/flux/v0.x/spec/lexical-elements/#string-literals).
```
Comment (bednar) [inline packages/core/src/query/flux.ts:42]: Maybe the `latest` will be better:
```suggestion
 * to become a [flux string literal](https://docs.influxdata.com/flux/latest/spec/lexical-elements/#string-literals).
```

**Review by bednar — APPROVED** [review]
Maybe we can change InfluxDB's links to `latest` version.

LGTM 🍻

**Review by bednar — APPROVED** [review]
